//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicercaLocalizzata.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RicercaLocalizzata.WPF.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anima.
        /// </summary>
        internal static string Anima {
            get {
                return ResourceManager.GetString("Anima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Cognome {
            get {
                return ResourceManager.GetString("Cognome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dati base.
        /// </summary>
        internal static string Dati_base {
            get {
                return ResourceManager.GetString("Dati_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzioni ciclo.
        /// </summary>
        internal static string Opzioni_ciclo {
            get {
                return ResourceManager.GetString("Opzioni_ciclo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzioni macchina.
        /// </summary>
        internal static string Opzioni_macchina {
            get {
                return ResourceManager.GetString("Opzioni_macchina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzioni sequenza.
        /// </summary>
        internal static string Opzioni_sequenza {
            get {
                return ResourceManager.GetString("Opzioni_sequenza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        internal static string Porta {
            get {
                return ResourceManager.GetString("Porta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anima Position.
        /// </summary>
        internal static string Posizione_Anima {
            get {
                return ResourceManager.GetString("Posizione_Anima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tacca bloccaggio.
        /// </summary>
        internal static string Tacca_Bloccaggio {
            get {
                return ResourceManager.GetString("Tacca_Bloccaggio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Tavolo {
            get {
                return ResourceManager.GetString("Tavolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tube type.
        /// </summary>
        internal static string Tipo_Tubo {
            get {
                return ResourceManager.GetString("Tipo_Tubo", resourceCulture);
            }
        }
    }
}
